### ISSUE TITLE
FEATURE - adding additional columns via config

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_google_ads_source#14]
**Are you a Fivetran customer?** 
Christoph Leinemann, Sustain.life

**Is your feature request related to a problem? Please describe.**
We are also pulling in conversion from all the ads packages. For some packages like linked in I can specify additional columns to be passed through via config.  For google I had to for this repo to add `all_conversions` to the macros

**Describe the solution you'd like**
I would like to a similar functionality as implemented in the LinkedIn pagackes where I can specify the following:

  linkedin__passthrough_metrics: [
      external_website_conversions,
      one_click_leads
    ] 

In the same way I'd like to specify a column from the source performance tables to be pulled into the toplevel adapters i.e. `all_conversions`

**Describe alternatives you've considered**

The alternative is to maintain our own version of the repo and add the column to the macro

**Additional context**

**Please indicate the level of urgency and business impact of this request** 

we currently have a workaround but I'd rather not be stuck on a fork.  I'd also be happy to contribute this if that's ok.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [X ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
@leinemann thanks for opening this Issue!

I am able to see what you are referring to within LinkedIn for allowing the pass through columns and will work to integrate this same functionality here as well. I will post back once we have a working branch you may test our before we integrate in a future release.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann this feature is now available in the latest `v0.4.0` release of the Fivetran Google Ads package! Feel free to upgrade your package to see these changes reflected and be sure to take a look at the README for notes on how to add your pass through columns.
