### ISSUE TITLE
BUG - Auto Tagged UTM Fields not Populating

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_google_ads_source#15]
**Are you a current Fivetran customer?** 

Yes, @MarkMacArdle at Bought By Many

This is a replica issue witch directly mirrors the request opened by Mark on [dbt_microsoft_ads_source](https://github.com/fivetran/dbt_microsoft_ads_source/issues/9)

**Comment by fivetran-joemarkiewicz** [comment]
@MarkMacArdle I was able to implement the same changes to the working branch noted within PR #16. 

It would be great if you would be able to give this a test run as well and let me know if all looks good on your end. I was able to leverage google's documentation and also the same functionality from Microsoft Ads to implement this feature. You can use the below config within your `packages.yml` to test out the branch.
```yml
packages:
    - git: https://github.com/fivetran/dbt_google_ads_source.git
      revision: feature/auto-tagging
      warn-unpinned: false
```
Let me know how it goes. Thanks!

**Comment by MarkMacArdle** [comment]
Hi @fivetran-joemarkiewicz this is working too. 

One slight annoyance is that when I click on some of our ads I see `utm_medium=paid-search` in the url, rather than `utm_medium=cpc`. When I tried to search what it should be I only found [this page](https://support.google.com/analytics/answer/1033981?hl=en#zippy=%2Cin-this-article) saying it should be `cpc` so, unless that difference is ringing a bell with you as to what might cause it, probably best left as is. Maybe we just have an override for the particular ads I've been clicking on. I don't think we need utm_medium for joining to the attribution data so it's not of much importance to us anyway.

**Comment by fivetran-joemarkiewicz** [comment]
Hmm the page you linked is what I referenced for this as well. I am not aware of the `paid-search` utm_medium. Could it possibly be that some utm's leverage the auto tagging feature while others do not? Additionally, is there anything else in the url you mentioned that would identify it as not being a cpc utm-medium?

**Comment by MarkMacArdle** [comment]
In Google's docs I did read that you could override the default utms so I guess we must be doing that. No sorry I didn't see a way identifying when utm_medium won't be the default.

**Comment by fivetran-joemarkiewicz** [comment]
I also would assume the overwritten utm_medium does not appear in the `effective_final_url ` field? I imagine not as the coalesce should have captured that if it was the case. I will continue to look a bit further into this to see if there is some other way to determine when a default auto-tag is overwritten.

**Comment by MarkMacArdle** [comment]
@fivetran-joemarkiewicz now that I look some of the ads actually do have utms in the `effective_final_url` and these are getting parsed out correctly in the `stg_google_ads__final_url_performance` table. If I do a `select distinct utm_medium,...` on that table I get a few rows back. Nearly all are `cpc` but there some `paid-search` ones.

Apologies for not checking this sooner. In the Microsoft Ads none of them had utm fields so I presumed it'd be the same here.

So does seem to be working fine.

**Comment by fivetran-joemarkiewicz** [comment]
That's great to hear! Thanks for checking on that. With this, I believe we are good to go for review of the PRs. I will coordinate with our team to review and will keep you updated in the respective tickets once we are able to release new versions of the Microsoft Ads and Google Ads source packages!

**Comment by fivetran-joemarkiewicz** [comment]
@MarkMacArdle I just published a new release which includes the PR resulted from this issue. The new dbt_google_ads_source `v0.3.1` should be live on the dbt hub at the top of the hour. 

Feel free to reopen this ticket if you have any further questions on this topic, or you can open another issue if you have any other questions. Thanks!
