### ISSUE TITLE
[Bug] Add dbt_expectations package dependency to README dependency section

### ISSUE THREAD

**Issue by fivetran-sheringuyen** [fivetran/dbt_google_ads_source#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The below should be added in the README dependencies section:

```
- package: calogica/dbt_expectations
  version: [">=0.5.0", "<0.6.0"]
```

### Expected behavior

N/A

### dbt Project configurations

N/A

### Package versions

N/A

### What database are you using dbt with?

bigquery

### dbt Version

N/A

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
PR #31 addresses this issue
