### ISSUE TITLE
[Bug] dbt_expectations <0.9.0 dependency

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_google_ads_source#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The latest version out of dbt-expectations is [0.9.0](https://github.com/calogica/dbt-expectations/releases/tag/0.9.0) and this package forces us to pin to an older version.

### Relevant error log or model output

```shell
N/A
```

### Expected behavior

Update the package to support 0.9.0

### dbt Project configurations

N/A

### Package versions

N/A

### What database are you using dbt with?

snowflake

### dbt Version

1.6

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-jamie** [comment]
Hi there @raphaelvarieras, thanks for opening this issue! 

I just tested the Google Ads packages out locally with v0.9.0 of dbt-expectations, and everything seems to work smoothly! Don't think we'll need to update anything other than the `packages.yml`. 

The team and I will get slot this in for our next sprint and just validate that there aren't any unintended consequences in our downstream [Ad Reporting](https://github.com/fivetran/dbt_ad_reporting) models

**Comment by fivetran-reneeli** [comment]
Thanks @raphaelvarieras for raising this! This has been included in our most recent [release](https://github.com/fivetran/dbt_google_ads_source/releases/tag/v0.9.4).

**Comment by fivetran-reneeli** [comment]
Never mind, taking that back. We didn't realize this was cause errors for those using our other packages that are also on the older version of dbt expectations. So we will be rolling this out universally instead. But in the meantime we will roll back this change

**Comment by jstingey** [comment]
@fivetran-reneeli imports of fivetran/ad_reporting is still failing dbt deps with the incompatible versions for dbt_expectations.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @jstingey can you confirm if this failure is still occurring?

**Comment by fivetran-joemarkiewicz** [comment]
For all following this thread - Our team will be working on making this update in our current sprint and will be making this a breaking change for the google (and downstream) packages so we may avoid dependency errors that were previously encountered by users.

We apologize for the failures that were caused as a result of the previous release and appreciate all of you working with us to correct the issue and forge a path forward for a better result to come with no unforeseen dependency errors.

**Comment by fivetran-reneeli** [comment]
Hi all, thanks for your patience! The updates will be provided in our next release in the following week.

**Comment by fivetran-catfritz** [comment]
This feature has been added to [v0.10.0](https://github.com/fivetran/dbt_google_ads_source/releases/tag/v0.10.0) and released today! Closing out this issue, but please continue to let us know any feedback!
