### ISSUE TITLE
FEATURE - Add an easy copy functionality for users to add fields to tables in Fivetran UI

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_google_ads_source#9]
**Are you a Fivetran customer?** 

Fivetran created Request

**Is your feature request related to a problem? Please describe.**
 
No problem. After setting up the required tables with a customer it was a bit tedius to add all fields into the Fivetran UI. If we can add a snippet section with comma separated fields then a customer would be able to easily copy/paste and move on.

**Describe the solution you'd like**
 
A snippet block with the fields for each required table to be comma separated so a customer can copy into Fivetran UI.

**Describe alternatives you've considered**
 
The alternative is how it currently is with bullets. Not ideal.

**Additional context**

N/A

**Please indicate the level of urgency and business impact of this request** 

Low - No pressing need, would be a nice to have low hanging fruit Issue to knock out.

**Comment by fivetran-jamie** [comment]
unfortunately i don't think this is possible in our UI -- i've tried separating by commas, `\n`, tabs, semi-colons, etc. i'm also definitely unable to batch-multi-select the fields from the dropdown, which is an ideal solution IMO. thinking we might just need to close this/mark as "won't do"

**Comment by fivetran-joemarkiewicz** [comment]
Hmm thanks for looking into this @fivetran-jamie and a shame we are not able to provide the copy/paste solution we were hoping to. We should log this internally to see what can be done to make the experience more seamless for customers, label this as `wontfix`, and close the issue.
